; generated by menu.js
; will be overwritten unless built with -M

STRING_PAUSE = stringPause-stringTable
STRING_BLOCK = stringBlock-stringTable
STRING_CLEAR = stringClear-stringTable
STRING_SURE = stringSure-stringTable
STRING_CONFETTI = stringConfetti-stringTable

.enum
MAIN_MENU
SUBMENU_NUMBERINPUTS
SUBMENU_BOOLEANINPUTS
SUBMENU_DIGITINPUTS
SUBMENU_NESTEDMENUS
SUBMENU_MORENESTED
SUBMENU_EVENMORE
SUBMENU_ANDMORE
SUBMENU_LASTONE
SUBMENU_V7MENUIDEAS
SUBMENU_TOURNAMENT
SUBMENU_DISPLAY
SUBMENU_CUSTOMCOLORS
SUBMENU_SETTINGS
.endenum

.enum
STRINGLIST_BOOL
STRINGLIST_ONOFF
STRINGLIST_SCORE
STRINGLIST_COLORS
STRINGLIST_STATS
STRINGLIST_CRASH
STRINGLIST_SPS
STRINGLIST_KILLWHEN
STRINGLIST_KILLHOW
STRINGLIST_DARK
STRINGLIST_EXAMPLES
STRINGLIST_THIS
STRINGLIST_EXAMPLES2
.endenum

; index activeMenu
firstPages:
    .byte $00
    .byte $02
    .byte $03
    .byte $04
    .byte $06
    .byte $07
    .byte $08
    .byte $09
    .byte $0A
    .byte $0B
    .byte $0C
    .byte $0D
    .byte $0E
    .byte $10

lastPages:
    .byte $02
    .byte $03
    .byte $04
    .byte $06
    .byte $07
    .byte $08
    .byte $09
    .byte $0A
    .byte $0B
    .byte $0C
    .byte $0D
    .byte $0E
    .byte $10
    .byte $11

; index activePage
pageTypes:
    .byte PAGE_MULTI | MODE_DEFAULT ; New Menu!
    .byte PAGE_MULTI | MODE_DEFAULT ; Second Page
    .byte PAGE_SINGLE | MODE_DEFAULT ; Numbers
    .byte PAGE_SINGLE | MODE_DEFAULT ; boolean
    .byte PAGE_MULTI | MODE_DEFAULT ; BCD Inputs
    .byte PAGE_MULTI | MODE_DEFAULT ; Hex Inputs
    .byte PAGE_SINGLE | MODE_DEFAULT ; Nested
    .byte PAGE_SINGLE | MODE_DEFAULT ; more nested
    .byte PAGE_SINGLE | MODE_DEFAULT ; even more
    .byte PAGE_SINGLE | MODE_DEFAULT ; and more
    .byte PAGE_SINGLE | MODE_DEFAULT ; last one
    .byte PAGE_SINGLE | MODE_DEFAULT ; Main Menu
    .byte PAGE_SINGLE | MODE_DEFAULT ; Tournament 
    .byte PAGE_SINGLE | MODE_DEFAULT ; Display Menu
    .byte PAGE_MULTI | MODE_DEFAULT ; Custom x0-x4
    .byte PAGE_MULTI | MODE_DEFAULT ; Custom x5-x9
    .byte PAGE_SINGLE | MODE_DEFAULT ; Settings

pageCounts:
    .byte $08
    .byte $01
    .byte $07
    .byte $04
    .byte $04
    .byte $04
    .byte $01
    .byte $01
    .byte $01
    .byte $01
    .byte $02
    .byte $03
    .byte $07
    .byte $08
    .byte $05
    .byte $05
    .byte $08

pageStringsetsHi:
    .byte >stringsetNewMenu ; New Menu!
    .byte >stringsetSecondPage ; Second Page
    .byte >stringsetNumbers ; Numbers
    .byte >stringsetBoolean ; boolean
    .byte >stringsetBcdInputs ; BCD Inputs
    .byte >stringsetHexInputs ; Hex Inputs
    .byte >stringsetNested ; Nested
    .byte >stringsetMoreNested ; more nested
    .byte >stringsetEvenMore ; even more
    .byte >stringsetAndMore ; and more
    .byte >stringsetLastOne ; last one
    .byte >stringsetMainMenu ; Main Menu
    .byte >stringsetTournament ; Tournament 
    .byte >stringsetDisplayMenu ; Display Menu
    .byte >stringsetCustomX0X4 ; Custom x0-x4
    .byte >stringsetCustomX5X9 ; Custom x5-x9
    .byte >stringsetSettings ; Settings

pageStringsetsLo:
    .byte <stringsetNewMenu ; New Menu!
    .byte <stringsetSecondPage ; Second Page
    .byte <stringsetNumbers ; Numbers
    .byte <stringsetBoolean ; boolean
    .byte <stringsetBcdInputs ; BCD Inputs
    .byte <stringsetHexInputs ; Hex Inputs
    .byte <stringsetNested ; Nested
    .byte <stringsetMoreNested ; more nested
    .byte <stringsetEvenMore ; even more
    .byte <stringsetAndMore ; and more
    .byte <stringsetLastOne ; last one
    .byte <stringsetMainMenu ; Main Menu
    .byte <stringsetTournament ; Tournament 
    .byte <stringsetDisplayMenu ; Display Menu
    .byte <stringsetCustomX0X4 ; Custom x0-x4
    .byte <stringsetCustomX5X9 ; Custom x5-x9
    .byte <stringsetSettings ; Settings

firstItems:
    .byte $00 ; NewMenu
    .byte $08 ; SecondPage
    .byte $09 ; Numbers
    .byte $10 ; Boolean
    .byte $14 ; BcdInputs
    .byte $18 ; HexInputs
    .byte $1C ; Nested
    .byte $1D ; MoreNested
    .byte $1E ; EvenMore
    .byte $1F ; AndMore
    .byte $20 ; LastOne
    .byte $22 ; MainMenu
    .byte $25 ; Tournament[Mode=Default]
    .byte $2C ; DisplayMenu
    .byte $34 ; CustomX0X4
    .byte $39 ; CustomX5X9
    .byte $3E ; Settings

; index activeItem
memoryMap:
    .byte <MEMORY_BASE + $00
    .byte <MEMORY_BASE + $01
    .byte <MEMORY_BASE + $02
    .byte <MEMORY_BASE + $06
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte <MEMORY_BASE + $0A
    .byte <MEMORY_BASE + $0B
    .byte <MEMORY_BASE + $0C
    .byte <MEMORY_BASE + $0D
    .byte <MEMORY_BASE + $0E
    .byte <MEMORY_BASE + $0F
    .byte <MEMORY_BASE + $10
    .byte <MEMORY_BASE + $11
    .byte <MEMORY_BASE + $12
    .byte <MEMORY_BASE + $13
    .byte <MEMORY_BASE + $14
    .byte <MEMORY_BASE + $15
    .byte <MEMORY_BASE + $16
    .byte <MEMORY_BASE + $18
    .byte <MEMORY_BASE + $1B
    .byte <MEMORY_BASE + $1F
    .byte <MEMORY_BASE + $20
    .byte <MEMORY_BASE + $22
    .byte <MEMORY_BASE + $25
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte <MEMORY_BASE + $29
    .byte <MEMORY_BASE + $2A
    .byte 0
    .byte 0
    .byte 0
    .byte <MEMORY_BASE + $2B
    .byte <MEMORY_BASE + $2C
    .byte <MEMORY_BASE + $2F
    .byte <MEMORY_BASE + $31
    .byte <MEMORY_BASE + $32
    .byte <MEMORY_BASE + $33
    .byte <MEMORY_BASE + $34
    .byte <MEMORY_BASE + $36
    .byte <MEMORY_BASE + $37
    .byte <MEMORY_BASE + $38
    .byte <MEMORY_BASE + $39
    .byte <MEMORY_BASE + $3A
    .byte <MEMORY_BASE + $3B
    .byte 0
    .byte <MEMORY_BASE + $3C
    .byte <MEMORY_BASE + $3D
    .byte <MEMORY_BASE + $40
    .byte <MEMORY_BASE + $43
    .byte <MEMORY_BASE + $46
    .byte <MEMORY_BASE + $49
    .byte <MEMORY_BASE + $4C
    .byte <MEMORY_BASE + $4F
    .byte <MEMORY_BASE + $52
    .byte <MEMORY_BASE + $55
    .byte <MEMORY_BASE + $58
    .byte <MEMORY_BASE + $5B
    .byte <MEMORY_BASE + $5C
    .byte <MEMORY_BASE + $5D
    .byte <MEMORY_BASE + $5E
    .byte <MEMORY_BASE + $5F
    .byte <MEMORY_BASE + $60
    .byte <MEMORY_BASE + $61
    .byte <MEMORY_BASE + $62

itemTypes:
    .byte TYPE_FF_OFF | $07 ; 0123456789ABCD
    .byte TYPE_CHOICES | STRINGLIST_EXAMPLES2 ; DCBA9876543210
    .byte TYPE_HEX | $08 ; C
    .byte TYPE_BCD | $08 ; D
    .byte TYPE_SUBMENU | SUBMENU_NUMBERINPUTS ; number inputs
    .byte TYPE_SUBMENU | SUBMENU_BOOLEANINPUTS ; boolean inputs
    .byte TYPE_SUBMENU | SUBMENU_DIGITINPUTS ; Digit Inputs
    .byte TYPE_SUBMENU | SUBMENU_NESTEDMENUS ; nested menus
    .byte TYPE_SUBMENU | SUBMENU_V7MENUIDEAS ; v7 menu ideas
    .byte TYPE_NUMBER | $02 ; Min Limit 2
    .byte TYPE_NUMBER | $1F ; Max Limit 30
    .byte TYPE_NUMBER | $00 ; Or Unlimited
    .byte TYPE_FF_OFF | $05 ; when -1 is off
    .byte TYPE_CHOICES | STRINGLIST_EXAMPLES2 ; from word list
    .byte TYPE_HEX | $02 ; by digit
    .byte TYPE_BCD | $02 ; by bcd digit
    .byte TYPE_BOOL ; Off On
    .byte TYPE_CHOICES | STRINGLIST_ONOFF ; ff means off
    .byte TYPE_NUMBER | $02 ; As Number
    .byte TYPE_CHOICES | STRINGLIST_EXAMPLES ; as words
    .byte TYPE_BCD | $02 ; BCD 2 Digit
    .byte TYPE_BCD | $04 ; BCD 4 Digit
    .byte TYPE_BCD | $06 ; BCD 6 Digit
    .byte TYPE_BCD | $08 ; BCD 8 Digit
    .byte TYPE_HEX | $02 ; HEX 2 Digit
    .byte TYPE_HEX | $04 ; HEX 4 Digit
    .byte TYPE_HEX | $06 ; HEX 6 Digit
    .byte TYPE_HEX | $08 ; HEX 8 Digit
    .byte TYPE_SUBMENU | SUBMENU_MORENESTED ; more nested
    .byte TYPE_SUBMENU | SUBMENU_EVENMORE ; even more
    .byte TYPE_SUBMENU | SUBMENU_ANDMORE ; and more
    .byte TYPE_SUBMENU | SUBMENU_LASTONE ; last one
    .byte TYPE_NUMBER | $08 ; foo
    .byte TYPE_CHOICES | STRINGLIST_THIS ; Dont do
    .byte TYPE_SUBMENU | SUBMENU_TOURNAMENT ; Tournament
    .byte TYPE_SUBMENU | SUBMENU_DISPLAY ; Display
    .byte TYPE_SUBMENU | SUBMENU_SETTINGS ; Settings
    .byte TYPE_CHOICES | STRINGLIST_SPS ; SPS
    .byte TYPE_HEX | $06 ; Piece Seed
    .byte TYPE_HEX | $04 ; B Seed
    .byte TYPE_CHOICES | STRINGLIST_KILLWHEN ; Killscreen
    .byte TYPE_CHOICES | STRINGLIST_KILLHOW ; how
    .byte TYPE_NUMBER | $00 ; Level
    .byte TYPE_BCD | $04 ; Lines
    .byte TYPE_CHOICES | STRINGLIST_SCORE ; Scoring
    .byte TYPE_FF_OFF | $10 ; Pace Display
    .byte TYPE_CHOICES | STRINGLIST_STATS ; Stats Box
    .byte TYPE_BOOL ; Input Display
    .byte TYPE_CHOICES | STRINGLIST_DARK ; Dark Mode
    .byte TYPE_CHOICES | STRINGLIST_COLORS ; Colors
    .byte TYPE_SUBMENU | SUBMENU_CUSTOMCOLORS ; Custom Colors
    .byte TYPE_BOOL ; Disable Flash
    .byte TYPE_HEX | $06 ; Lvl x0
    .byte TYPE_HEX | $06 ; Lvl x1
    .byte TYPE_HEX | $06 ; Lvl x2
    .byte TYPE_HEX | $06 ; Lvl x3
    .byte TYPE_HEX | $06 ; Lvl x4
    .byte TYPE_HEX | $06 ; Lvl x5
    .byte TYPE_HEX | $06 ; Lvl x6
    .byte TYPE_HEX | $06 ; Lvl x7
    .byte TYPE_HEX | $06 ; Lvl x8
    .byte TYPE_HEX | $06 ; Lvl x9
    .byte TYPE_CHOICES | STRINGLIST_CRASH ; Crash
    .byte TYPE_BOOL ; Strict Crash
    .byte TYPE_BOOL ; Disable Pause
    .byte TYPE_BOOL ; Goofy Foot
    .byte TYPE_BOOL ; Das Only
    .byte TYPE_BOOL ; Qual Mode
    .byte TYPE_BOOL ; Block Tool
    .byte TYPE_BOOL ; Pal Mode

stringListIndexes:
    .byte stringListBool-stringLists
    .byte stringListOnoff-stringLists
    .byte stringListScore-stringLists
    .byte stringListColors-stringLists
    .byte stringListStats-stringLists
    .byte stringListCrash-stringLists
    .byte stringListSps-stringLists
    .byte stringListKillwhen-stringLists
    .byte stringListKillhow-stringLists
    .byte stringListDark-stringLists
    .byte stringListExamples-stringLists
    .byte stringListThis-stringLists
    .byte stringListExamples2-stringLists

stringListCounts:
    .byte $02
    .byte $02
    .byte $05
    .byte $04
    .byte $04
    .byte $04
    .byte $03
    .byte $03
    .byte $04
    .byte $05
    .byte $02
    .byte $01
    .byte $03

stringLists:
stringListBool:
    .byte stringOff-stringTable
    .byte stringOn-stringTable
stringListOnoff:
    .byte stringOn-stringTable
    .byte stringOff-stringTable
stringListScore:
    .byte stringClassic-stringTable
    .byte stringLetters-stringTable
    .byte string7digit-stringTable
    .byte stringM-stringTable
    .byte stringHidden-stringTable
stringListColors:
    .byte stringVanilla-stringTable
    .byte stringPride-stringTable
    .byte stringWhite-stringTable
    .byte stringCustom-stringTable
stringListStats:
    .byte stringStats-stringTable
    .byte stringHzDsply-stringTable
    .byte stringDasmeter-stringTable
    .byte stringNothing-stringTable
stringListCrash:
    .byte stringOff-stringTable
    .byte stringShown-stringTable
    .byte stringTopout-stringTable
    .byte stringCrash-stringTable
stringListSps:
    .byte stringOff-stringTable
    .byte stringOn-stringTable
    .byte stringSimilar-stringTable
stringListKillwhen:
    .byte stringOff-stringTable
    .byte stringLines-stringTable
    .byte stringLevel-stringTable
stringListKillhow:
    .byte stringKs2-stringTable
    .byte stringFloor-stringTable
    .byte stringInviz-stringTable
    .byte stringHalt-stringTable
stringListDark:
    .byte stringOff-stringTable
    .byte stringOn-stringTable
    .byte stringLite-stringTable
    .byte stringTeal-stringTable
    .byte stringOg-stringTable
stringListExamples:
    .byte stringFoo-stringTable
    .byte stringBar-stringTable
stringListThis:
    .byte stringThis-stringTable
stringListExamples2:
    .byte stringFoo-stringTable
    .byte stringBar-stringTable
    .byte stringBaz-stringTable

stringTable:
stringOff:
    .byte $03,"O","F","F"
stringOn:
    .byte $02,"O","N"
stringClassic:
    .byte $07,"C","L","A","S","S","I","C"
stringLetters:
    .byte $07,"L","E","T","T","E","R","S"
string7digit:
    .byte $06,"7","D","I","G","I","T"
stringM:
    .byte $01,"M"
stringHidden:
    .byte $06,"H","I","D","D","E","N"
stringVanilla:
    .byte $07,"V","A","N","I","L","L","A"
stringPride:
    .byte $05,"P","R","I","D","E"
stringWhite:
    .byte $05,"W","H","I","T","E"
stringCustom:
    .byte $06,"C","U","S","T","O","M"
stringStats:
    .byte $05,"S","T","A","T","S"
stringHzDsply:
    .byte $08,"H","Z",$EF,"D","S","P","L","Y"
stringDasmeter:
    .byte $08,"D","A","S","M","E","T","E","R"
stringNothing:
    .byte $07,"N","O","T","H","I","N","G"
stringShown:
    .byte $05,"S","H","O","W","N"
stringTopout:
    .byte $06,"T","O","P","O","U","T"
stringCrash:
    .byte $05,"C","R","A","S","H"
stringSimilar:
    .byte $07,"S","I","M","I","L","A","R"
stringLines:
    .byte $05,"L","I","N","E","S"
stringLevel:
    .byte $05,"L","E","V","E","L"
stringKs2:
    .byte $04,"K","S",$69,"2"
stringFloor:
    .byte $05,"F","L","O","O","R"
stringInviz:
    .byte $05,"I","N","V","I","Z"
stringHalt:
    .byte $04,"H","A","L","T"
stringLite:
    .byte $04,"L","I","T","E"
stringTeal:
    .byte $04,"T","E","A","L"
stringOg:
    .byte $02,"O","G"
stringFoo:
    .byte $03,"F","O","O"
stringBar:
    .byte $03,"B","A","R"
stringThis:
    .byte $04,"T","H","I","S"
stringBaz:
    .byte $03,"B","A","Z"
stringPause:
    .byte $05,"P","A","U","S","E"
stringBlock:
    .byte $05,"B","L","O","C","K"
stringClear:
    .byte $06,"C","L","E","A","R","?"
stringSure:
    .byte $06,"S","U","R","E","?","!"
stringConfetti:
    .byte $08,"C","O","N","F","E","T","T","I"

.out .sprintf("%d/256 sprite string bytes", * - stringTable)


stringsetNewMenu:
    .byte "N","E","W",$EF,"M","E","N","U","!"
    .byte EOL
    .byte "0","1","2","3","4","5","6","7","8","9","A","B","C","D"
    .byte EOL
    .byte "D","C","B","A","9","8","7","6","5","4","3","2","1","0"
    .byte EOL
    .byte "C"
    .byte EOL
    .byte "D"
    .byte EOL
    .byte "N","U","M","B","E","R",$EF,"I","N","P","U","T","S"
    .byte EOL
    .byte "B","O","O","L","E","A","N",$EF,"I","N","P","U","T","S"
    .byte EOL
    .byte "D","I","G","I","T",$EF,"I","N","P","U","T","S"
    .byte EOL
    .byte "N","E","S","T","E","D",$EF,"M","E","N","U","S"
    .byte EOF
stringsetSecondPage:
    .byte "S","E","C","O","N","D",$EF,"P","A","G","E"
    .byte EOL
    .byte "V","7",$EF,"M","E","N","U",$EF,"I","D","E","A","S"
    .byte EOF
stringsetNumbers:
    .byte "N","U","M","B","E","R","S"
    .byte EOL
    .byte "M","I","N",$EF,"L","I","M","I","T",$EF,"2"
    .byte EOL
    .byte "M","A","X",$EF,"L","I","M","I","T",$EF,"3","0"
    .byte EOL
    .byte "O","R",$EF,"U","N","L","I","M","I","T","E","D"
    .byte EOL
    .byte "W","H","E","N",$EF,"-","1",$EF,"I","S",$EF,"O","F","F"
    .byte EOL
    .byte "F","R","O","M",$EF,"W","O","R","D",$EF,"L","I","S","T"
    .byte EOL
    .byte "B","Y",$EF,"D","I","G","I","T"
    .byte EOL
    .byte "B","Y",$EF,"B","C","D",$EF,"D","I","G","I","T"
    .byte EOF
stringsetBoolean:
    .byte "B","O","O","L","E","A","N"
    .byte EOL
    .byte "O","F","F",$EF,"O","N"
    .byte EOL
    .byte "F","F",$EF,"M","E","A","N","S",$EF,"O","F","F"
    .byte EOL
    .byte "A","S",$EF,"N","U","M","B","E","R"
    .byte EOL
    .byte "A","S",$EF,"W","O","R","D","S"
    .byte EOF
stringsetBcdInputs:
    .byte "B","C","D",$EF,"I","N","P","U","T","S"
    .byte EOL
    .byte "B","C","D",$EF,"2",$EF,"D","I","G","I","T"
    .byte EOL
    .byte "B","C","D",$EF,"4",$EF,"D","I","G","I","T"
    .byte EOL
    .byte "B","C","D",$EF,"6",$EF,"D","I","G","I","T"
    .byte EOL
    .byte "B","C","D",$EF,"8",$EF,"D","I","G","I","T"
    .byte EOF
stringsetHexInputs:
    .byte "H","E","X",$EF,"I","N","P","U","T","S"
    .byte EOL
    .byte "H","E","X",$EF,"2",$EF,"D","I","G","I","T"
    .byte EOL
    .byte "H","E","X",$EF,"4",$EF,"D","I","G","I","T"
    .byte EOL
    .byte "H","E","X",$EF,"6",$EF,"D","I","G","I","T"
    .byte EOL
    .byte "H","E","X",$EF,"8",$EF,"D","I","G","I","T"
    .byte EOF
stringsetNested:
    .byte "N","E","S","T","E","D"
    .byte EOL
    .byte "M","O","R","E",$EF,"N","E","S","T","E","D"
    .byte EOF
stringsetMoreNested:
    .byte "M","O","R","E",$EF,"N","E","S","T","E","D"
    .byte EOL
    .byte "E","V","E","N",$EF,"M","O","R","E"
    .byte EOF
stringsetEvenMore:
    .byte "E","V","E","N",$EF,"M","O","R","E"
    .byte EOL
    .byte "A","N","D",$EF,"M","O","R","E"
    .byte EOF
stringsetAndMore:
    .byte "A","N","D",$EF,"M","O","R","E"
    .byte EOL
    .byte "L","A","S","T",$EF,"O","N","E"
    .byte EOF
stringsetLastOne:
    .byte "L","A","S","T",$EF,"O","N","E"
    .byte EOL
    .byte "F","O","O"
    .byte EOL
    .byte "D","O","N","T",$EF,"D","O"
    .byte EOF
stringsetMainMenu:
    .byte "M","A","I","N",$EF,"M","E","N","U"
    .byte EOL
    .byte "T","O","U","R","N","A","M","E","N","T"
    .byte EOL
    .byte "D","I","S","P","L","A","Y"
    .byte EOL
    .byte "S","E","T","T","I","N","G","S"
    .byte EOF
stringsetTournament:
    .byte "T","O","U","R","N","A","M","E","N","T",$EF
    .byte EOL
    .byte "S","P","S"
    .byte EOL
    .byte "P","I","E","C","E",$EF,"S","E","E","D"
    .byte EOL
    .byte "B",$EF,"S","E","E","D"
    .byte EOL
    .byte "K","I","L","L","S","C","R","E","E","N"
    .byte EOL
    .byte "H","O","W"
    .byte EOL
    .byte "L","E","V","E","L"
    .byte EOL
    .byte "L","I","N","E","S"
    .byte EOF
stringsetDisplayMenu:
    .byte "D","I","S","P","L","A","Y",$EF,"M","E","N","U"
    .byte EOL
    .byte "S","C","O","R","I","N","G"
    .byte EOL
    .byte "P","A","C","E",$EF,"D","I","S","P","L","A","Y"
    .byte EOL
    .byte "S","T","A","T","S",$EF,"B","O","X"
    .byte EOL
    .byte "I","N","P","U","T",$EF,"D","I","S","P","L","A","Y"
    .byte EOL
    .byte "D","A","R","K",$EF,"M","O","D","E"
    .byte EOL
    .byte "C","O","L","O","R","S"
    .byte EOL
    .byte "C","U","S","T","O","M",$EF,"C","O","L","O","R","S"
    .byte EOL
    .byte "D","I","S","A","B","L","E",$EF,"F","L","A","S","H"
    .byte EOF
stringsetCustomX0X4:
    .byte "C","U","S","T","O","M",$EF,"X","0","-","X","4"
    .byte EOL
    .byte "L","V","L",$EF,"X","0"
    .byte EOL
    .byte "L","V","L",$EF,"X","1"
    .byte EOL
    .byte "L","V","L",$EF,"X","2"
    .byte EOL
    .byte "L","V","L",$EF,"X","3"
    .byte EOL
    .byte "L","V","L",$EF,"X","4"
    .byte EOF
stringsetCustomX5X9:
    .byte "C","U","S","T","O","M",$EF,"X","5","-","X","9"
    .byte EOL
    .byte "L","V","L",$EF,"X","5"
    .byte EOL
    .byte "L","V","L",$EF,"X","6"
    .byte EOL
    .byte "L","V","L",$EF,"X","7"
    .byte EOL
    .byte "L","V","L",$EF,"X","8"
    .byte EOL
    .byte "L","V","L",$EF,"X","9"
    .byte EOF
stringsetSettings:
    .byte "S","E","T","T","I","N","G","S"
    .byte EOL
    .byte "C","R","A","S","H"
    .byte EOL
    .byte "S","T","R","I","C","T",$EF,"C","R","A","S","H"
    .byte EOL
    .byte "D","I","S","A","B","L","E",$EF,"P","A","U","S","E"
    .byte EOL
    .byte "G","O","O","F","Y",$EF,"F","O","O","T"
    .byte EOL
    .byte "D","A","S",$EF,"O","N","L","Y"
    .byte EOL
    .byte "Q","U","A","L",$EF,"M","O","D","E"
    .byte EOL
    .byte "B","L","O","C","K",$EF,"T","O","O","L"
    .byte EOL
    .byte "P","A","L",$EF,"M","O","D","E"
    .byte EOF


